/* Seed de démonstration : 24 QCM médicaux fictifs mais plausibles, avec mots-clés. */
const API = 'http://localhost:3001/api';

const questions = [
  { statement: "Devant une fibrillation atriale rapide avec instabilité hémodynamique, quelle est la prise en charge de première intention ?", options: ["Amiodarone IV en dose de charge", "Cardioversion électrique en urgence", "Bêtabloquant per os", "Anticoagulation seule et surveillance"], correct: [1], explanation: "L'instabilité hémodynamique impose une cardioversion électrique immédiate (recommandations ESC).", tags: ["démonstration", "cardiologie", "urgences"] },
  { statement: "Quel est le traitement de première intention de l'hypertension artérielle chez le patient diabétique ?", options: ["Bêtabloquant", "IEC ou ARA II", "Diurétique thiazidique", "Inhibiteur calcique"], correct: [1], explanation: "Les bloqueurs du SRAA sont privilégiés pour leur néphroprotection.", tags: ["démonstration", "cardiologie", "diabetologie"] },
  { statement: "Quelle est la valeur seuil de troponine pour le diagnostic d'infarctus du myocarde ?", options: ["Au-dessus du 99e percentile avec cinétique", "Toute valeur détectable", "Le double de la normale", "Il n'y a pas de seuil défini"], correct: [0], explanation: "Définition universelle : élévation au-dessus du 99e percentile avec cinétique évocatrice.", tags: ["démonstration", "cardiologie", "biologie"] },
  { statement: "Devant une suspicion d'embolie pulmonaire avec probabilité clinique faible, quel examen demander en premier ?", options: ["Angioscanner thoracique d'emblée", "D-dimères", "Scintigraphie pulmonaire", "Échographie cardiaque"], correct: [1], explanation: "Les D-dimères ont une excellente valeur prédictive négative en probabilité faible.", tags: ["démonstration", "pneumologie", "urgences"] },
  { statement: "Quel est le germe le plus fréquent des pneumonies communautaires de l'adulte ?", options: ["Haemophilus influenzae", "Mycoplasma pneumoniae", "Streptococcus pneumoniae", "Legionella pneumophila"], correct: [2], explanation: "Le pneumocoque reste le premier agent des PAC.", tags: ["démonstration", "pneumologie", "infectiologie"] },
  { statement: "Quels sont les critères d'un asthme aigu grave ? (plusieurs réponses)", options: ["DEP < 30 % de la théorique", "Impossibilité de parler", "Fréquence cardiaque > 120/min", "Sibilants bruyants"], correct: [0, 1, 2], explanation: "Les sibilants bruyants ne sont pas un critère de gravité — le silence auscultatoire, si.", tags: ["démonstration", "pneumologie", "urgences"] },
  { statement: "Quelle est la première cause d'insuffisance rénale chronique terminale en Europe ?", options: ["Glomérulonéphrites", "Polykystose rénale", "Néphropathie diabétique", "Néphropathies vasculaires"], correct: [2], explanation: "La néphropathie diabétique est la première cause d'IRCT.", tags: ["démonstration", "nephrologie", "diabetologie"] },
  { statement: "Quel ionogramme évoque une insuffisance surrénalienne aiguë ?", options: ["Hyponatrémie + hyperkaliémie", "Hypernatrémie + hypokaliémie", "Hyponatrémie + hypokaliémie", "Ionogramme normal"], correct: [0], explanation: "Le déficit en aldostérone entraîne fuite sodée et rétention potassique.", tags: ["démonstration", "endocrinologie", "urgences"] },
  { statement: "Devant une céphalée brutale « en coup de tonnerre », quel diagnostic évoquer en priorité ?", options: ["Migraine avec aura", "Hémorragie sous-arachnoïdienne", "Céphalée de tension", "Algie vasculaire de la face"], correct: [1], explanation: "Toute céphalée en coup de tonnerre est une HSA jusqu'à preuve du contraire.", tags: ["démonstration", "neurologie", "urgences"] },
  { statement: "Quel est le délai maximal pour une thrombolyse IV dans l'AVC ischémique ?", options: ["3 heures", "4 h 30", "6 heures", "12 heures"], correct: [1], explanation: "4 h 30 après le début des symptômes, sous conditions.", tags: ["démonstration", "neurologie", "urgences"] },
  { statement: "Quel signe clinique différencie une paralysie faciale centrale d'une périphérique ?", options: ["L'atteinte du territoire supérieur du visage", "La présence de troubles du goût", "L'épargne du territoire supérieur du visage", "L'hyperacousie"], correct: [2], explanation: "Le territoire supérieur est épargné dans l'atteinte centrale (double innervation).", tags: ["démonstration", "neurologie"] },
  { statement: "Quelle est la triade du syndrome méningé ?", options: ["Céphalées, vomissements, raideur de nuque", "Fièvre, confusion, convulsions", "Céphalées, photophobie, fièvre", "Raideur, purpura, coma"], correct: [0], explanation: "La triade classique ; la fièvre oriente vers une méningite.", tags: ["démonstration", "neurologie", "infectiologie"] },
  { statement: "Devant une hyperglycémie avec cétonurie chez un diabétique de type 1, quelle est la priorité thérapeutique ?", options: ["Insuline IV à la seringue électrique", "Réhydratation", "Bicarbonates", "Potassium d'emblée"], correct: [1], explanation: "La réhydratation précède l'insulinothérapie dans l'acidocétose.", tags: ["démonstration", "diabetologie", "urgences"] },
  { statement: "Quel est l'objectif d'HbA1c chez la plupart des diabétiques de type 2 ?", options: ["< 6 %", "≤ 7 %", "≤ 8 %", "≤ 9 %"], correct: [1], explanation: "7 % pour la plupart des patients, à individualiser.", tags: ["démonstration", "diabetologie"] },
  { statement: "Quelle biologie évoque une hémolyse ? (plusieurs réponses)", options: ["Haptoglobine effondrée", "LDH élevées", "Bilirubine libre élevée", "Ferritine effondrée"], correct: [0, 1, 2], explanation: "La ferritine n'est pas un marqueur d'hémolyse.", tags: ["démonstration", "hematologie", "biologie"] },
  { statement: "Quel antidote pour un surdosage en paracétamol ?", options: ["Naloxone", "Flumazénil", "N-acétylcystéine", "Vitamine K"], correct: [2], explanation: "La NAC reconstitue le stock de glutathion hépatique.", tags: ["démonstration", "toxicologie", "urgences"] },
  { statement: "Devant une douleur abdominale de la fosse iliaque droite avec défense, quel diagnostic évoquer en premier chez l'adulte jeune ?", options: ["Colique néphrétique", "Appendicite aiguë", "Sigmoïdite", "Cholécystite"], correct: [1], explanation: "Localisation et défense : appendicite jusqu'à preuve du contraire.", tags: ["démonstration", "chirurgie", "urgences"] },
  { statement: "Quel est l'examen de référence pour le diagnostic de cholécystite aiguë ?", options: ["Scanner abdominal", "Échographie abdominale", "IRM hépatique", "ASP"], correct: [1], explanation: "L'échographie : paroi > 4 mm, Murphy échographique, calculs.", tags: ["démonstration", "chirurgie", "gastroenterologie"] },
  { statement: "Quelle est la conduite immédiate devant une anaphylaxie de grade III ?", options: ["Corticoïdes IV", "Antihistaminiques", "Adrénaline IM 0,5 mg", "Remplissage seul"], correct: [2], explanation: "L'adrénaline IM est le traitement de première intention, sans délai.", tags: ["démonstration", "urgences", "allergologie"] },
  { statement: "Quel score évalue le risque d'AVC dans la fibrillation atriale ?", options: ["CHA2DS2-VASc", "HAS-BLED", "Wells", "GRACE"], correct: [0], explanation: "CHA2DS2-VASc pour le risque embolique ; HAS-BLED pour le risque hémorragique.", tags: ["démonstration", "cardiologie"] },
  { statement: "Quelle vitamine supplémenter systématiquement chez la femme enceinte en périconceptionnel ?", options: ["Vitamine D", "Acide folique (B9)", "Vitamine B12", "Fer"], correct: [1], explanation: "0,4 mg/j d'acide folique en prévention des anomalies de fermeture du tube neural.", tags: ["démonstration", "gynecologie", "prevention"] },
  { statement: "Quel est le premier examen devant une suspicion de pyélonéphrite aiguë simple ?", options: ["Uroscanner", "BU puis ECBU", "Échographie rénale", "Hémocultures seules"], correct: [1], explanation: "Bandelette urinaire puis ECBU avant antibiothérapie.", tags: ["démonstration", "nephrologie", "infectiologie"] },
  { statement: "Signes de gravité d'une hyperkaliémie à l'ECG ? (plusieurs réponses)", options: ["Ondes T amples et pointues", "Élargissement des QRS", "Disparition des ondes P", "Sous-décalage de PR"], correct: [0, 1, 2], explanation: "Ondes T pointues, QRS larges, disparition des P : urgence thérapeutique.", tags: ["démonstration", "cardiologie", "nephrologie", "urgences"] },
  { statement: "Quelle est la durée d'anticoagulation d'une EP provoquée par un facteur transitoire ?", options: ["6 semaines", "3 mois", "6 mois", "À vie"], correct: [1], explanation: "3 mois pour une EP avec facteur déclenchant réversible.", tags: ["démonstration", "pneumologie", "hematologie"] }
];

const HEADERS = { 'Content-Type': 'application/json' };
const existing = new Set((await fetch(API + '/questions', { headers: HEADERS }).then(r => r.json())).map(q => q.statement));
let n = 0;
for (const q of questions) {
  if (existing.has(q.statement)) continue;
  const res = await fetch(API + '/questions', { method: 'POST', headers: HEADERS, body: JSON.stringify(q) });
  if (!res.ok) console.error('FAIL', q.statement.slice(0, 40), await res.text()); else n++;
}
console.log('Seeded', n, 'new questions (', existing.size, 'already present )');
